version: '3.8'

services:
  bookmark-db:
    image: postgres:latest
    container_name: bookmark-postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookmark-db
    networks:
      - freecodecamp-bookmark

networks:
  freecodecamp-bookmark:
